// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order.Api.Infrastructure;

namespace Order.Api.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20190102021908_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Order.Api.Models.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("MultipleOrders");

                    b.Property<string>("Name");

                    b.Property<int>("TimeOfDay");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new { Id = new Guid("01dc2b47-158f-4d55-b84f-19fb1bce6468"), MultipleOrders = false, Name = "Eggs", TimeOfDay = 1, Type = 1 },
                        new { Id = new Guid("f29b1e83-b789-43a9-9f3b-020e1c5c8f4d"), MultipleOrders = false, Name = "Toast", TimeOfDay = 1, Type = 2 },
                        new { Id = new Guid("47734caf-4c93-4d50-bfb1-69ca830351cc"), MultipleOrders = true, Name = "Coffee", TimeOfDay = 1, Type = 3 },
                        new { Id = new Guid("2969d37e-a1d1-40fe-ba2e-4d7955335ddf"), MultipleOrders = false, Name = "Steak", TimeOfDay = 2, Type = 1 },
                        new { Id = new Guid("4d2a0198-5bde-4110-9e17-e4df59a5d79f"), MultipleOrders = true, Name = "Potato", TimeOfDay = 2, Type = 2 },
                        new { Id = new Guid("3962523f-7c1e-448a-95fc-c79438160e98"), MultipleOrders = false, Name = "Wine", TimeOfDay = 2, Type = 3 },
                        new { Id = new Guid("5276811a-1777-42bb-a16f-0584b9ba71d2"), MultipleOrders = false, Name = "Cake", TimeOfDay = 2, Type = 4 }
                    );
                });

            modelBuilder.Entity("Order.Api.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Input");

                    b.Property<string>("Output");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
